### PR TITLE
Add help menu

### PR DESCRIPTION
**Pull request by hstejas**
Add a new menu entry with '?' that prints the help message

### CODE REVIEW

**Comment by hstejas** [comment]
This is what it looks like when used.

```
D 1: Favorites
D 2: Continue Watching
D 3: Next Up
D 4: Latest Added
D 5: User Views
> ?
S ::= "q" (quits)
    | "h" (go to "home" root menu)
    | ".." (go to previous menu)
    | "?" (Print this help message)
    | "f" ( "c" | [pufrld]+ ) (filters: clear or played, unplayed, favourite, resumable, liked, disliked)
    | "m" ("p" | "u") Selector (marks items played or unplayed)
    | Selector (opens a single directory entry or sends a sequence of items to playback)
    Selector :: = '*' (everything in the current menu)
    | Items
    Items ::= Atom "," Items (list)
    | Atom
    Atom ::= n1 "-" n2 (range)
    | n (single item)
```

**Comment by Aanok** [comment]
Hi! Very nice : ) I'm gonna merge this right away when I get home tonight. Probably also alias it to a "help" command.

This had been a task on the todo list since forever. Thanks!

**Comment by hstejas** [comment]
:) 
Now that i look at it again, I had copied the help text from README, but the leg file has more options.
Also should this this be `.leg` like or should this be more human readable?

**Comment by Aanok** [comment]
The only thing that's missing is search and it's good that it remains unsupported until I get it implemented properly (one day...).

You're good!

**Pull request merged**
